title: Al lot of blog
author: amcclead
email: amclead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test for my actual blog/resume site

# social links
twitter_username: your-twitter-handle
github_username:  amcclead

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
